### PR TITLE
perfect view social buttons in option

### PR DESCRIPTION
**Pull request by Toxblh**
I do few correct style for perfect view option

before:
screen2

after:
screnshot

### CODE REVIEW

**Comment by softvar** [comment]
Though the change looks good, but I never encountered this issue myself.
Can you please tell me how did you reproduce it? Environment specific?

**Comment by Toxblh** [comment]
This is Windows 10, and chrome browser latest version on today.
Maybe this my small monitor :), resolution 1024x768 pixels

**Comment by Toxblh** [comment]
I test on my work mac, I download extension from store, latest on today version chrome (v54.0.2840.98). ...and I see the some.
screen shot 2016-11-16 at 09 12 13

**Comment by Toxblh** [comment]
Can you merge, if approved the PR?

**Comment by softvar** [comment]
Thanks @Toxblh for the fix

**Pull request merged**
