### PR TITLE
More native Download Icon's CSS Styling Resolves #4

### LINKED ISSUE #4: About the Icons
@s0ftvar Nice one. It's a bit buggy, though. Downloading dotfiles convert them to something like gitignore.txt. Also, can you downtone these icons to be grey in color and a bit more minimal icons? Like this http://cloud.ahmda.ws/rYOl31L so that the UI doesn't feel overwhelming? 

I think `#999` color would do. 
A bit padding-left would be great. Something like http://cloud.ahmda.ws/Yc8AbJ1
Thanks!

### PR DESCRIPTION
**Pull request by ahmadawais**
More Native Download Icon's CSS Styling resolves #4.

### CODE REVIEW

**Comment by ahmadawais** [comment]
More native padding now.

**Comment by softvar** [comment]
This is great!

@ahmadawais Can you please add the hover effect too? The same old blue color on hover? That would give it a good look and an indication of some actionable thing.

**Comment by ahmadawais** [comment]
@softvar No I can't and I won't.

**Can't** add hover via inline CSS.
**Won't** add hover effect coz it will not be native. You can check the file icon, when you hover it, there is no hover effect in GitHub. Let's keep things as native as we can?

**Comment by ahmadawais** [comment]
@softvar It's been a long time. You never merged this PR.

**Comment by softvar** [comment]
@ahmadawais Hey, my mistake.
I talked with other UI guys around me, it turns out that blue color is much more prominent than the default grayish color.
The Blue color actually implies there's something actionable and is.

Consider this screenshot - https://www.dropbox.com/s/g4ia0kybn7vinqa/Screenshot%202016-10-27%2016.29.07.png?dl=0 , anything which is clickable turns blue on hover to indicate some action. Here, as you earlier mentioned, we don't' have any way to add pseudo classes, so I think it's better to show download icon in blue colour by default to let user know of it's implication.

Thanks for the patch though.

**Pull request closed without merging**
